"""
╔══════════════════════════════════════════════════════════════════════════════╗
║                     NexusScope — PostgreSQL Connection Pool                 ║
║                  Manages async connections to Neon PostgreSQL               ║
╚══════════════════════════════════════════════════════════════════════════════╝

RESPONSIBILITIES
────────────────
 ✓  Pool initialization at startup
 ✓  Automatic schema migration (creates scans table if it doesn't exist)
 ✓  Connection lifecycle management
 ✓  Query helpers for S3 leak hunting module

USAGE
─────
From any async context:
    from backend.database import get_pool, get_connection
    
    pool = get_pool()  # Returns singleton connection pool
    async with pool.acquire() as conn:
        result = await conn.fetchrow("SELECT * FROM scans WHERE id = $1", task_id)
"""

import asyncpg
import os
from typing import Optional
from uuid import UUID
import json
import logging

logger = logging.getLogger("database")

# ─────────────────────────────────────────────
#  §1  SINGLETON POOL
# ─────────────────────────────────────────────
_DB_POOL: Optional[asyncpg.Pool] = None


def get_pool() -> asyncpg.Pool:
    """
    Returns the active connection pool.
    
    RAISES:
        RuntimeError if pool has not been initialized via initialize_pool()
    
    USAGE:
        pool = get_pool()
        async with pool.acquire() as conn:
            result = await conn.fetchrow("SELECT ...")
    """
    if _DB_POOL is None:
        raise RuntimeError(
            "Database pool not initialized. "
            "Call initialize_pool() in app startup event."
        )
    return _DB_POOL


# ─────────────────────────────────────────────
#  §2  POOL INITIALIZATION & SCHEMA SETUP
#  ─────────────────────────────────────────────
async def initialize_pool() -> asyncpg.Pool:
    """
    Creates and initializes the PostgreSQL connection pool.
    
    This function:
      1. Connects to the DATABASE_URL
      2. Creates the asyncpg.Pool with optimized settings
      3. Runs schema migrations (creates tables if they don't exist)
      4. Stores the pool in _DB_POOL module variable
      5. Returns the pool for storage in app.state if needed
    
    REQUIRED ENV VARS:
        DATABASE_URL: PostgreSQL connection string
                      Format: postgresql://user:pass@host:port/dbname?sslmode=require
    
    RAISES:
        asyncpg.PostgresError: If connection fails
        asyncpg.UndefinedColumnError: If schema migration fails
    
    USAGE (in FastAPI startup event):
        @app.on_event("startup")
        async def startup():
            await initialize_pool()
            logger.info("Database pool initialized")
    """
    global _DB_POOL
    
    database_url = os.getenv(
        "DATABASE_URL",
        "postgresql://neondb_owner:npg_1UZoIlXY9hdP@ep-super-surf-a56q8o4p-pooler"
        ".us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
    )
    
    try:
        _DB_POOL = await asyncpg.create_pool(
            database_url,
            min_size=5,                    # Minimum connections to maintain
            max_size=20,                   # Maximum connections in pool
            max_queries=50000,             # Max queries per connection before reset
            max_cached_statement_lifetime=300,  # Statement cache TTL
            max_cacheable_statement_size=15000,  # Max statement size to cache
            command_timeout=10,            # Timeout for individual commands
            timeout=30,                    # Connection timeout
        )
        
        logger.info("✓ Connected to PostgreSQL via asyncpg")
        
        # Run schema migrations
        await _create_schema()
        
        return _DB_POOL
        
    except asyncpg.PostgresError as e:
        logger.error(f"✗ Failed to initialize DB pool: {e}")
        raise


async def _create_schema():
    """
    Creates the scans table if it doesn't exist.
    
    TABLE: scans
    ────────────
      id             UUID PRIMARY KEY       — Unique scan identifier (generated by FastAPI)
      target_domain  TEXT NOT NULL          — Domain being scanned (e.g., "example.com")
      status         TEXT NOT NULL          — One of: 'running', 'completed', 'failed'
      results        JSONB DEFAULT '{}'::jsonb  — Scan results as JSON (buckets found, errors, etc.)
      created_at     TIMESTAMPTZ DEFAULT NOW()  — Scan start time
      updated_at     TIMESTAMPTZ DEFAULT NOW()  — Last update time
    
    INDICES:
      - PRIMARY on id (auto-created)
      - Status lookup for dashboard queries
    """
    pool = get_pool()
    
    async with pool.acquire() as conn:
        await conn.execute("""
            CREATE TABLE IF NOT EXISTS scans (
                id UUID PRIMARY KEY,
                target_domain TEXT NOT NULL,
                status TEXT NOT NULL CHECK (status IN ('running', 'completed', 'failed')),
                results JSONB DEFAULT '{}'::jsonb,
                created_at TIMESTAMPTZ DEFAULT NOW(),
                updated_at TIMESTAMPTZ DEFAULT NOW()
            );
        """)
        
        # Create indices for faster queries
        await conn.execute("""
            CREATE INDEX IF NOT EXISTS idx_scans_status 
            ON scans(status);
        """)
        
        await conn.execute("""
            CREATE INDEX IF NOT EXISTS idx_scans_created_at 
            ON scans(created_at DESC);
        """)
        
        logger.info("✓ Schema migration complete (scans table ready)")


# ─────────────────────────────────────────────
#  §3  HELPER FUNCTIONS FOR S3 LEAK HUNTING
#  ─────────────────────────────────────────────
async def insert_scan(task_id: UUID, target_domain: str) -> None:
    """
    Inserts a new scan record with status='running'.
    
    PARAMS:
        task_id: UUID for this scan task
        target_domain: Domain being scanned (e.g., "example.com")
    
    RAISES:
        asyncpg.UniqueViolationError: If scan with same ID already exists
    
    USAGE:
        await insert_scan(uuid.uuid4(), "example.com")
    """
    pool = get_pool()
    
    async with pool.acquire() as conn:
        await conn.execute("""
            INSERT INTO scans (id, target_domain, status, results)
            VALUES ($1, $2, 'running', '{}')
        """, task_id, target_domain)
        
        logger.info(f"✓ Inserted scan record: {task_id} for {target_domain}")


async def update_scan_results(
    task_id: UUID,
    status: str,
    results: dict
) -> None:
    """
    Updates a scan record's status and results after completion.
    
    PARAMS:
        task_id: UUID of the scan to update
        status: New status ('completed' or 'failed')
        results: Dictionary of bucket findings or error details
    
    RAISES:
        asyncpg.PostgresError: If update fails
    
    USAGE:
        await update_scan_results(
            task_id,
            "completed",
            {"open_buckets": [...], "total_checked": 50}
        )
    """
    pool = get_pool()
    
    async with pool.acquire() as conn:
        await conn.execute("""
            UPDATE scans
            SET status = $2, results = $3, updated_at = NOW()
            WHERE id = $1
        """, task_id, status, json.dumps(results))
        
        logger.info(f"✓ Updated scan {task_id} with status={status}")


async def get_scan(task_id: UUID) -> Optional[dict]:
    """
    Retrieves a scan record by UUID.
    
    RETURNS:
        Dictionary with keys: id, target_domain, status, results, created_at, updated_at
        Or None if scan not found
    
    USAGE:
        scan = await get_scan(uuid.UUID("550e8400-e29b-41d4-a716-446655440000"))
        if scan:
            print(f"Scan status: {scan['status']}")
    """
    pool = get_pool()
    
    async with pool.acquire() as conn:
        row = await conn.fetchrow(
            "SELECT * FROM scans WHERE id = $1",
            task_id
        )
        
        if row:
            return dict(row)
        return None


async def close_pool():
    """
    Closes the connection pool gracefully.
    
    USAGE (in FastAPI shutdown event):
        @app.on_event("shutdown")
        async def shutdown():
            await close_pool()
            logger.info("Database pool closed")
    """
    global _DB_POOL
    
    if _DB_POOL is not None:
        await _DB_POOL.close()
        _DB_POOL = None
        logger.info("✓ Database pool closed")
